package ru.yandex.practicum.filmorate.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "MPA_Ratings") // Имя таблицы совпадает с именем в SQL
public class MPARating {

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY) // Соответствует GENERATED BY DEFAULT AS IDENTITY
  @Column(name = "MPARating_id") // Имя столбца в таблице
  private Integer id;

  @Column(name = "MPA_Rating_name", nullable = false, length = 255) // Имя и ограничения для столбца
  private String name;
}